set_project("Drast")
set_version("0.1.0")
set_languages("c++17")

add_rules("mode.debug", "mode.release")

local project_root = os.projectdir()
local source_main = path.join(project_root, "src", "main.drast")
local generated_root = path.join(project_root, "build", "generated")
local bootstrap_cpp = path.join(generated_root, "bootstrap", "transpiler.cpp")
local bootstrap_bin = path.join(project_root, "build", "bootstrap", "transpiler_bootstrap")
local selfhost_cpp = path.join(generated_root, "selfhost", "transpiler.cpp")
local selfcheck_cpp = path.join(generated_root, "selfhost-check", "transpiler.cpp")
local selfcheck_bin = path.join(project_root, "build", "selfhost-check", "transpiler_selfhost")
local prebuilt = path.join(project_root, "dist", "drastc-darwin-arm64")

target("bootstrap")
    set_kind("binary")
    set_default(false)
    on_build(function ()
        local cxx = os.getenv("CXX") or "clang++"
        assert(os.isfile(prebuilt), "missing bootstrap compiler: " .. prebuilt)
        os.mkdir(path.directory(bootstrap_cpp))
        os.execv(prebuilt, {source_main, "-o", bootstrap_cpp})
        os.mkdir(path.directory(bootstrap_bin))
        os.execv(cxx, {"-std=c++17", "-I" .. project_root, bootstrap_cpp, "-o", bootstrap_bin})
    end)

target("transpiler")
    set_kind("binary")
    set_default(true)
    set_languages("c++17")
    set_toolset("cxx", "clang++")
    set_toolset("ld", "clang++")
    add_deps("bootstrap")
    add_includedirs(project_root)
    add_files(selfhost_cpp, {always_added = true})
    before_build(function ()
        if not os.isfile(bootstrap_bin) then
            local cxx = os.getenv("CXX") or "clang++"
            assert(os.isfile(prebuilt), "missing bootstrap compiler: " .. prebuilt)
            os.mkdir(path.directory(bootstrap_cpp))
            os.execv(prebuilt, {source_main, "-o", bootstrap_cpp})
            os.mkdir(path.directory(bootstrap_bin))
            os.execv(cxx, {"-std=c++17", "-I" .. project_root, bootstrap_cpp, "-o", bootstrap_bin})
        end
        os.mkdir(path.directory(selfhost_cpp))
        os.execv(bootstrap_bin, {source_main, "-o", selfhost_cpp})
    end)

target("self-host")
    set_kind("binary")
    set_default(false)
    add_deps("transpiler")
    on_build(function ()
        import("core.project.project")
        local cxx = os.getenv("CXX") or "clang++"
        local compiler = project.target("transpiler"):targetfile()
        assert(os.isfile(compiler), "transpiler target did not create: " .. compiler)
        os.mkdir(path.directory(selfcheck_cpp))
        os.execv(compiler, {source_main, "-o", selfcheck_cpp})
        os.mkdir(path.directory(selfcheck_bin))
        os.execv(cxx, {"-std=c++17", "-I" .. project_root, selfcheck_cpp, "-o", selfcheck_bin})
        os.execv(selfcheck_bin, {source_main, "-o", path.join(generated_root, "selfhost-check", "transpiler.second.cpp")})
    end)

target("test")
    set_kind("binary")
    set_default(false)
    add_deps("self-host")
    on_build(function ()
        os.execv(path.join(project_root, "scripts", "run_tests.sh"), {selfcheck_bin, project_root})
    end)
