// Auto-generated by `drast headers` for target `test`.
// Drop-in implementation: compile this file together with test.h.
// Regenerated on every `drast headers` invocation; this file is read-only.
// Do not edit by hand.
#include "test.h"

Ledger::Ledger(std::string title, std::vector<int> entries)
    : title(std::move(title)),
      entries(std::move(entries)),
      cached(0) {}

int Ledger::total() const {
    int sum = 0;
    for (const auto& entry : this->entries) {
        sum += entry;
    }
    return sum;
}

void Ledger::rename(const std::string& next) {
    this->title = next;
}

int readNode(const int& node) {
    return node;
}

