// Auto-generated by `drast headers` for target `test`.
// This file is regenerated on every `drast headers` invocation and is
// installed read-only. Do not edit by hand.
#ifndef DRAST_TEST_H
#define DRAST_TEST_H

#include <cstddef>
#include <cstdint>
#include <memory>
#include <optional>
#include <string>
#include <tuple>
#include <unordered_map>
#include <variant>
#include <vector>

struct Ledger;

struct Ledger {
    std::string title;
    std::vector<int> entries;
  private:
    int cached;
  public:
    Ledger(std::string title, std::vector<int> entries);
    int total() const;
    void rename(const std::string& next);
};

int readNode(int& node);

#endif // DRAST_TEST_H
